app_name: gpii-express-user

git_repository: https://github.com/the-t-in-rtf/gpii-express-user.git

email: tony@raisingthefloor.org

env_runtime: linux-desktop

app_start_service: false

software_stack: nodejs

software_stack_version: 4.3.1

setup:
  - sudo npm install -g bower
  - sudo yum -y install java-1.8.0-openjdk-devel.x86_64
  - npm install

commands:
  - npm test