# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-express-user
    git_repository: https://github.com/the-t-in-rtf/gpii-express-user.git
    git_branch: GPII-1754
    software_stack: nodejs
    software_stack_version: lts
    folder:
      dest: /app/gpii-express-user
    run_in: fedora
    deploy: false
    setup:
      - sudo yum -y install java-1.8.0-openjdk-devel.x86_64
      - yarn install
    test_cmds:
      - yarn test