name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    env:
      HEADLESS: true
      BROWSERS: chrome

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Node Tests
        run: npm run test:node

      - name: Stop all Docker containers
        run: docker rm -f $(docker ps -q -a)

      - name: Browser Tests
        run: npm run test:webdriver

      - name: Create Coverage Reports
        run: npm run posttest

      - name: Save Code Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports
