name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x]

    env:
      HEADLESS: true
      BROWSERS: chrome

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Code
        run: $(npm bin)/grunt lint

      - name: Node Tests
        run: xvfb-run --auto-servernum npm test

      - name: Stop Docker Containers
        run: docker rm -f $(docker ps -q -a)

      - name: Browser Tests
        run: npm run test:webdriver

      - name: Cleanup after xvfb
        uses: bcomnes/cleanup-xvfb@v1

      - name: Code Coverage
        run: npm run posttest
